### ISSUE TITLE
Specifying a non-existing security manager fails with: fatal error: ExceptionMark destructor expects no pending exceptions

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#139]
```
cthaling@macbook:~/ws/graal-jvmci-8/graal-jvmci-8$ ./jdk1.8.0_65/product/bin/java -Djava.security.manager=java.lang.SecurityManager -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit JVMCI VM (build 25.66-b00-internal-jvmci-0.9-dev, mixed mode)
```

```
cthaling@macbook:~/ws/graal-jvmci-8/graal-jvmci-8$ ./jdk1.8.0_65/product/bin/java -Djava.security.manager=foo -version
java.lang.InternalError 
 - klass: 'java/lang/InternalError'
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (exceptions.cpp:427), pid=20096, tid=5891
#  fatal error: ExceptionMark destructor expects no pending exceptions
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: OpenJDK 64-Bit JVMCI VM (25.66-b00-internal-jvmci-0.9-dev mixed mode bsd-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/cthaling/ws/graal-jvmci-8/graal-jvmci-8/hs_err_pid20096.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Abort trap: 6
```

**Comment by tkrodriguez** [comment]
This appears to be caused by this change which came out of the JDK9 review.

@@ -3579,10 +3654,7 @@
   // Note that we do not use CHECK_0 here since we are inside an EXCEPTION_MARK and
   // set_init_completed has just been called, causing exceptions not to be shortcut
   // anymore. We call vm_exit_during_initialization directly instead.
-  SystemDictionary::compute_java_system_loader(THREAD);
-  if (HAS_PENDING_EXCEPTION) {
-    vm_exit_during_initialization(Handle(THREAD, PENDING_EXCEPTION));
-  }
+  SystemDictionary::compute_java_system_loader(CHECK_(JNI_ERR));

It's returning with a pending exception.  Anyone know why this change was made?  It's from this changeset.

$ hg log -r 22423
changeset:   22423:4a532b03e2cd
user:        Doug Simon <doug.simon@oracle.com>
date:        Fri Aug 14 15:35:08 2015 +0200
summary:     some fixes and improvements based on JEP 243 review

**Comment by tkrodriguez** [comment]
The EXCEPTION_MARK was removed in 9.  It's nice how the comment still references it though.  We should just undo that change in 8.

**Comment by tkrodriguez** [comment]
Fixed by Doug in https://lafo.ssw.uni-linz.ac.at/hg/graal-jvmci-8/rev/b364269cb6cf
