### ISSUE TITLE
BytecodeParser.inline should print HotSpotPrintInlining messages

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#180]
While looking into a compilation issue I noticed that inlining during parsing was not printed with HotSpotPrintInlining.  This should be added.

**Comment by zapster** [comment]
Hey Chris! Thanks for your report. I have added `PrintInlining` support to the bytecode parser in 1968f7eeeb1. Please note, however, that the output produced by the inlining phase (i.e. late inlining, not done during bytecode parsing) might not look as expected. More precisely, late inlining does not print its messages in a tree-like fashion since it is, in general, not greedy but worklist based. If you want to debug/inspect Graal inlining I suggest using other options like `-Dgraal.Log=Inlining`, `-Dgraal.Log=InliningDecisions:2` or dump the graph to IGV, e.g. with `-Dgraal.Dump=,:GraphBuilderPhase:2` and `-Dgraal.DumpDuringGraphBuilding=true`.
