### ISSUE TITLE
Push a maven artifact for Graal on some schedule

### ISSUE THREAD

**Issue by headius** [graalvm/graal-core#269]
There is currently no way to add a dependency on Graal to a Maven build because there are no published Graal binaries in Maven central (or in any other repository).

This makes it difficult to build any package that uses Graal and has a Maven build. I am doing this currently to customize Graal for JRuby. Currently I have to set Maven to use a local jar, which means I can't release anything to Maven due to the local file dependency.

Can we fix?

**Comment by dougxc** [comment]
Graal jars are somewhat complicated artifacts and don't necessarily play well with the maven model. They have a dependency on JVMCI which is an external library on JDK8 but comes with JDK9. We always build against the JDK8 JVMCI jars to ensure compatibility but this involves quite some mx trickery when using a JDK9 javac to ensure the external JVMCI jars are compiled against instead of the JVMCI classes in the JDK (using the latter requires a whole bunch of `--add-exports` command line options since most JVMCI packages are not exported in JDK9). I'm not sure how you would implement these special build requirements with maven.

That said, being open source, you could upload Graal (and Truffle) binaries to maven in a name space you own if you can make maven work with the above complications.

Keep in mind that there is currently no official Graal API.

We plan to publish Truffle API jars to Maven central at some point. (/cc @chumer @thomaswue)

**Comment by dougxc** [comment]
@headius , I'd like to close this issue unless you have insights on how to address the above complications of using Graal jars in maven.
