### ISSUE TITLE
Graal "Hello World" prose

### ISSUE THREAD

**Issue by tedneward** [graalvm/graal-core#274]
After going through the docs, I can't figure out what the "hello world" of Graal is, by way of getting started with it or verifying that it is working correctly. Where do I begin with this, once I get it built?

**Comment by dougxc** [comment]
Once you've built by following the directions in https://github.com/graalvm/graal/blob/master/compiler/README.md, then "hello world" is to compile a HelloWorld.java class and run it:
```
mx vm HelloWorld
```
This almost certainly won't trigger any Graal compilations however since HelloWorld won't be hot. I'm not sure what you're interested in, but maybe https://github.com/graalvm/graal/blob/master/compiler/docs/Debugging.md#inspecting-the-compilation-of-a-single-method is an interesting place to start.
